#!/usr/bin/env bash

if [ -d out ]; then
	find out/ -maxdepth 1 -mindepth 1 -exec rm -rf {} \;
fi

export DEBUG="*,-mquery,-data/connection,-babel,-agenda*"

clear
echo -en "Building The App\n"
node_modules/.bin/tsc --pretty --project tsconfig.json
